name: Build Qt Project

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.0'
        modules: 'qt.quickcontrols2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/qt'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ github.workspace }}/qt/6.7.0/msvc2019_64"

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload Artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: QtDashboardTemplate-Windows
        path: build/Release/QtDashboardTemplate.exe
