name: Validate Project

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check required files exist
      run: |
        test -f CMakeLists.txt
        test -f src/main.cpp
        test -f src/qml/main.qml
        test -f src/backend/backend.h
        echo "? All required files present"

    - name: Validate CMakeLists.txt syntax (basic)
      run: |
        grep -q "cmake_minimum_required" CMakeLists.txt
        grep -q "find_package(Qt6" CMakeLists.txt
        echo "? CMakeLists.txt looks valid"
